@extends('layouts.app')

@section('title', 'System Health Reports')

@section('content')

    <!-- Header -->
    <div class="d-flex flex-wrap align-items-center justify-content-between gap-3 mb-4">
        <div>
            <h3 class="fw-bold text-dark mb-1">
                <i class="bi bi-file-earmark-bar-graph text-primary me-2"></i>Web Health & Availability Reports
            </h3>
            <p class="text-muted mb-0 small">Generate comprehensive periodic uptime, response latency, and SLA compliance reports</p>
        </div>
        <div>
            <a href="{{ route('reports.create') }}" class="btn btn-psca d-flex align-items-center gap-2">
                <i class="bi bi-plus-circle"></i>
                <span>Generate New Report</span>
            </a>
        </div>
    </div>

    <!-- Reports Grid / Cards -->
    <div class="row g-4">
        @forelse($reports as $report)
            <div class="col-md-6 col-xl-4">
                <div class="card card-custom h-100 position-relative">
                    <div class="card-body p-4 d-flex flex-column">
                        <div class="d-flex align-items-center justify-content-between mb-2">
                            <span class="badge bg-primary-subtle text-primary border border-primary-subtle px-2 py-1 small">
                                <i class="bi bi-calendar-range me-1"></i>
                                {{ $report->period_from->format('d M Y') }} &ndash; {{ $report->period_to->format('d M Y') }}
                            </span>
                            @if($report->uptime_percentage >= 99.0)
                                <span class="badge bg-success-subtle text-success border border-success-subtle fw-bold">
                                    {{ $report->uptime_percentage }}% Uptime
                                </span>
                            @elseif($report->uptime_percentage >= 95.0)
                                <span class="badge bg-warning-subtle text-warning border border-warning-subtle fw-bold">
                                    {{ $report->uptime_percentage }}% Uptime
                                </span>
                            @else
                                <span class="badge bg-danger-subtle text-danger border border-danger-subtle fw-bold">
                                    {{ $report->uptime_percentage }}% Uptime
                                </span>
                            @endif
                        </div>

                        <h5 class="fw-bold text-dark mb-1">{{ $report->title }}</h5>
                        <p class="small text-muted mb-3">Generated by: {{ $report->user?->name ?? 'System' }} &middot; {{ $report->created_at->format('d M Y, h:i A') }}</p>

                        <!-- Progress Bar -->
                        <div class="mb-3">
                            <div class="d-flex justify-content-between small text-muted mb-1">
                                <span>Availability SLA</span>
                                <strong class="text-dark">{{ $report->uptime_percentage }}%</strong>
                            </div>
                            <div class="progress" style="height: 8px;">
                                <div class="progress-bar {{ $report->uptime_percentage >= 98 ? 'bg-success' : ($report->uptime_percentage >= 90 ? 'bg-warning' : 'bg-danger') }}"
                                     role="progressbar"
                                     style="width: {{ $report->uptime_percentage }}%;"
                                ></div>
                            </div>
                        </div>

                        <!-- Stats Mini Row -->
                        <div class="row g-2 mb-4 text-center mt-auto">
                            <div class="col-4">
                                <div class="bg-light p-2 rounded-2">
                                    <small class="text-muted d-block" style="font-size: 0.72rem;">CHECKS</small>
                                    <strong class="text-dark">{{ $report->total_checks }}</strong>
                                </div>
                            </div>
                            <div class="col-4">
                                <div class="bg-success-subtle p-2 rounded-2">
                                    <small class="text-success d-block" style="font-size: 0.72rem;">PASSED</small>
                                    <strong class="text-success">{{ $report->successful_checks }}</strong>
                                </div>
                            </div>
                            <div class="col-4">
                                <div class="bg-danger-subtle p-2 rounded-2">
                                    <small class="text-danger d-block" style="font-size: 0.72rem;">FAILED</small>
                                    <strong class="text-danger">{{ $report->failed_checks }}</strong>
                                </div>
                            </div>
                        </div>

                        <!-- Card Action Buttons -->
                        <div class="d-flex align-items-center justify-content-between border-top pt-3">
                            <a href="{{ route('reports.show', $report) }}" class="btn btn-sm btn-psca">
                                <i class="bi bi-eye me-1"></i> View Report
                            </a>
                            <div class="d-flex gap-1">
                                <a href="{{ route('reports.print', $report) }}" target="_blank" class="btn btn-sm btn-outline-secondary" title="Printable Report">
                                    <i class="bi bi-printer"></i>
                                </a>
                                <form method="POST" action="{{ route('reports.destroy', $report) }}" onsubmit="return confirm('Delete this report?');" class="d-inline">
                                    @csrf
                                    @method('DELETE')
                                    <button type="submit" class="btn btn-sm btn-outline-danger" title="Delete Report">
                                        <i class="bi bi-trash"></i>
                                    </button>
                                </form>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        @empty
            <div class="col-12">
                <div class="card card-custom text-center py-5">
                    <div class="card-body">
                        <i class="bi bi-file-earmark-bar-graph fs-1 d-block mb-3 text-secondary opacity-50"></i>
                        <h5 class="fw-bold text-dark">No Health Reports Generated Yet</h5>
                        <p class="text-muted small mb-4">Generate comprehensive uptime reports for any past date range based on recorded monitoring logs.</p>
                        <a href="{{ route('reports.create') }}" class="btn btn-psca">
                            <i class="bi bi-plus-circle me-1"></i> Generate First Report
                        </a>
                    </div>
                </div>
            </div>
        @endforelse
    </div>

    @if($reports->hasPages())
        <div class="mt-4">
            {{ $reports->links('pagination::bootstrap-5') }}
        </div>
    @endif

@endsection
