<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Health Report - {{ $report->title }}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <style>
        body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; color: #1e293b; background: #fff; }
        .report-header { border-bottom: 2px solid #1a3a5c; padding-bottom: 15px; margin-bottom: 25px; }
        .table th { background: #f1f5f9 !important; color: #334155; font-size: 0.8rem; text-transform: uppercase; }
        @media print {
            .no-print { display: none !important; }
            body { padding: 0; }
        }
    </style>
</head>
<body class="p-4">

    <!-- Print Control Bar -->
    <div class="no-print mb-4 d-flex justify-content-between align-items-center bg-light p-3 rounded border">
        <div>
            <span class="fw-bold">Report Print / Export Preview</span>
        </div>
        <div class="d-flex gap-2">
            <button onclick="window.print()" class="btn btn-primary btn-sm">
                Print / Save as PDF
            </button>
            <button onclick="window.close()" class="btn btn-secondary btn-sm">
                Close Window
            </button>
        </div>
    </div>

    <!-- Header -->
    <div class="report-header d-flex justify-content-between align-items-center">
        <div>
            <h2 class="fw-bold text-dark mb-1">{{ config('app.name', 'PSCA') }} Web Health & Performance Audit</h2>
            <h4 class="text-primary mb-1">{{ $report->title }}</h4>
            <p class="text-muted mb-0 small">
                Audit Period: <strong>{{ $report->period_from->format('d M Y') }} to {{ $report->period_to->format('d M Y') }}</strong>
            </p>
        </div>
        <div class="text-end">
            <div class="small text-muted">Generated by: {{ $report->user?->name ?? 'System' }}</div>
            <div class="small text-muted">Date: {{ $report->created_at->format('d M Y, h:i A') }}</div>
            <div class="badge bg-primary fs-6 mt-2">{{ $report->uptime_percentage }}% Uptime SLA</div>
        </div>
    </div>

    <!-- Executive Metrics Row -->
    <div class="row g-3 mb-4 text-center">
        <div class="col-3">
            <div class="border p-3 rounded">
                <small class="text-muted text-uppercase fw-bold">Overall Uptime</small>
                <div class="fs-3 fw-bold text-success">{{ $report->uptime_percentage }}%</div>
            </div>
        </div>
        <div class="col-3">
            <div class="border p-3 rounded">
                <small class="text-muted text-uppercase fw-bold">Total Checks</small>
                <div class="fs-3 fw-bold text-dark">{{ $report->total_checks }}</div>
            </div>
        </div>
        <div class="col-3">
            <div class="border p-3 rounded">
                <small class="text-muted text-uppercase fw-bold">Passing (UP)</small>
                <div class="fs-3 fw-bold text-success">{{ $report->successful_checks }}</div>
            </div>
        </div>
        <div class="col-3">
            <div class="border p-3 rounded">
                <small class="text-muted text-uppercase fw-bold">Failed / Incidents</small>
                <div class="fs-3 fw-bold text-danger">{{ $report->failed_checks }}</div>
            </div>
        </div>
    </div>

    <!-- Detailed Website Metrics -->
    <h5 class="fw-bold mb-3">Individual Web Assets Availability & Response Times</h5>
    <table class="table table-bordered table-sm align-middle mb-5">
        <thead>
            <tr>
                <th>Target Website</th>
                <th class="text-center" style="width: 110px;">Total Checks</th>
                <th class="text-center" style="width: 110px;">Uptime Checks</th>
                <th class="text-center" style="width: 110px;">Downtime</th>
                <th class="text-center" style="width: 130px;">Uptime Ratio</th>
                <th class="text-end" style="width: 130px;">Avg Latency</th>
            </tr>
        </thead>
        <tbody>
            @foreach($report->reportWebsites as $rw)
                <tr>
                    <td>
                        <div class="fw-bold">{{ $rw->website?->name ?? 'Deleted Site' }}</div>
                        <small class="text-muted">{{ $rw->website?->url }}</small>
                    </td>
                    <td class="text-center">{{ $rw->total_checks }}</td>
                    <td class="text-center text-success fw-bold">{{ $rw->uptime_count }}</td>
                    <td class="text-center text-danger fw-bold">{{ $rw->downtime_count }}</td>
                    <td class="text-center fw-bold {{ $rw->uptime_percentage >= 98 ? 'text-success' : 'text-danger' }}">
                        {{ $rw->uptime_percentage }}%
                    </td>
                    <td class="text-end font-monospace">{{ $rw->avg_response_time_seconds }}s</td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <!-- Footer Signature / Stamp Area -->
    <div class="row pt-5 mt-5">
        <div class="col-6">
            <div class="border-top pt-2 text-center" style="width: 250px;">
                <small class="text-muted">Prepared By (System Officer)</small>
            </div>
        </div>
        <div class="col-6 d-flex justify-content-end">
            <div class="border-top pt-2 text-center" style="width: 250px;">
                <small class="text-muted">Verified By (Director IT / PSCA)</small>
            </div>
        </div>
    </div>

</body>
</html>
