@extends('layouts.app')

@section('title', 'Health Report: ' . $report->title)

@section('content')

    <!-- Report Header & Actions -->
    <div class="d-flex flex-wrap align-items-center justify-content-between gap-3 mb-4">
        <div>
            <div class="small text-muted mb-1">
                <a href="{{ route('reports.index') }}" class="text-decoration-none text-muted">
                    <i class="bi bi-arrow-left me-1"></i> Back to Reports
                </a>
            </div>
            <h3 class="fw-bold text-dark mb-0">
                <i class="bi bi-file-earmark-check text-primary me-2"></i>{{ $report->title }}
            </h3>
            <p class="text-muted mb-0 small mt-1">
                Period: <strong>{{ $report->period_from->format('d M Y') }} &ndash; {{ $report->period_to->format('d M Y') }}</strong> &middot;
                Generated by: <strong>{{ $report->user?->name ?? 'System' }}</strong> &middot;
                Generated on: {{ $report->created_at->format('d M Y, h:i A') }}
            </p>
        </div>
        <div class="d-flex gap-2">
            <a href="{{ route('reports.print', $report) }}" target="_blank" class="btn btn-outline-secondary d-flex align-items-center gap-1">
                <i class="bi bi-printer"></i>
                <span>Print / PDF Export</span>
            </a>
            <form method="POST" action="{{ route('reports.destroy', $report) }}" onsubmit="return confirm('Delete this report?');" class="d-inline">
                @csrf
                @method('DELETE')
                <button type="submit" class="btn btn-outline-danger" title="Delete Report">
                    <i class="bi bi-trash"></i>
                </button>
            </form>
        </div>
    </div>

    <!-- Executive SLA Summary Cards -->
    <div class="row g-3 mb-4">
        <!-- Overall Uptime -->
        <div class="col-sm-6 col-xl-3">
            <div class="card bg-white border p-3 rounded-3 shadow-sm text-center h-100">
                <div class="small text-muted text-uppercase fw-semibold">Overall Availability SLA</div>
                <div class="fs-1 fw-bold {{ $report->uptime_percentage >= 98 ? 'text-success' : ($report->uptime_percentage >= 90 ? 'text-warning' : 'text-danger') }} mt-1">
                    {{ $report->uptime_percentage }}%
                </div>
                <div class="progress mt-2" style="height: 6px;">
                    <div class="progress-bar {{ $report->uptime_percentage >= 98 ? 'bg-success' : 'bg-warning' }}" style="width: {{ $report->uptime_percentage }}%;"></div>
                </div>
            </div>
        </div>

        <!-- Total Checks -->
        <div class="col-sm-6 col-xl-3">
            <div class="card bg-white border p-3 rounded-3 shadow-sm text-center h-100">
                <div class="small text-muted text-uppercase fw-semibold">Total Monitoring Checks</div>
                <div class="fs-1 fw-bold text-dark mt-1">{{ $report->total_checks }}</div>
                <small class="text-muted">Recorded across period</small>
            </div>
        </div>

        <!-- Successful Checks -->
        <div class="col-sm-6 col-xl-3">
            <div class="card bg-success-subtle border border-success-subtle p-3 rounded-3 shadow-sm text-center h-100">
                <div class="small text-success text-uppercase fw-semibold">Operational (UP) Checks</div>
                <div class="fs-1 fw-bold text-success mt-1">{{ $report->successful_checks }}</div>
                <small class="text-success opacity-75">Passing health SLA</small>
            </div>
        </div>

        <!-- Failed Checks -->
        <div class="col-sm-6 col-xl-3">
            <div class="card bg-danger-subtle border border-danger-subtle p-3 rounded-3 shadow-sm text-center h-100">
                <div class="small text-danger text-uppercase fw-semibold">Failed / Downtime Incidents</div>
                <div class="fs-1 fw-bold text-danger mt-1">{{ $report->failed_checks }}</div>
                <small class="text-danger opacity-75">Recorded outages</small>
            </div>
        </div>
    </div>

    <!-- Website Breakdown Table -->
    <div class="card card-custom mb-4">
        <div class="card-header bg-white border-bottom py-3">
            <h5 class="mb-0 fw-bold text-dark">
                <i class="bi bi-diagram-3 me-2 text-primary"></i>Website Availability & Latency Breakdown
            </h5>
        </div>
        <div class="table-responsive">
            <table class="table table-custom table-hover align-middle mb-0">
                <thead>
                    <tr>
                        <th>Website Name & URL</th>
                        <th style="width: 130px;" class="text-center">Total Checks</th>
                        <th style="width: 120px;" class="text-center">Uptime Count</th>
                        <th style="width: 120px;" class="text-center">Downtime</th>
                        <th style="width: 220px;">Uptime Compliance</th>
                        <th style="width: 150px;" class="text-end">Avg Latency</th>
                    </tr>
                </thead>
                <tbody>
                    @forelse($report->reportWebsites as $rw)
                        <tr>
                            <td>
                                <div class="fw-bold text-dark">{{ $rw->website?->name ?? 'Unknown Site' }}</div>
                                <div class="small text-muted">{{ $rw->website?->url ?? '#' }}</div>
                            </td>
                            <td class="text-center fw-bold">{{ $rw->total_checks }}</td>
                            <td class="text-center text-success fw-bold">{{ $rw->uptime_count }}</td>
                            <td class="text-center text-danger fw-bold">{{ $rw->downtime_count }}</td>
                            <td>
                                <div class="d-flex align-items-center gap-2">
                                    <div class="progress flex-grow-1" style="height: 8px;">
                                        <div class="progress-bar {{ $rw->uptime_percentage >= 98 ? 'bg-success' : ($rw->uptime_percentage >= 90 ? 'bg-warning' : 'bg-danger') }}"
                                             style="width: {{ $rw->uptime_percentage }}%;"
                                        ></div>
                                    </div>
                                    <span class="small fw-bold {{ $rw->uptime_percentage >= 98 ? 'text-success' : 'text-danger' }}">
                                        {{ $rw->uptime_percentage }}%
                                    </span>
                                </div>
                            </td>
                            <td class="text-end font-monospace fw-semibold text-primary">
                                {{ $rw->avg_response_time_seconds }}s
                            </td>
                        </tr>
                    @empty
                        <tr>
                            <td colspan="6" class="text-center py-4 text-muted">No website metrics recorded for this period.</td>
                        </tr>
                    @endforelse
                </tbody>
            </table>
        </div>
    </div>

    <!-- Recorded Incidents Log in Period -->
    @if($incidentLogs->count() > 0)
        <div class="card card-custom">
            <div class="card-header bg-white border-bottom py-3">
                <h5 class="mb-0 fw-bold text-danger">
                    <i class="bi bi-exclamation-octagon me-2"></i>Recorded Failure Incidents in Report Period ({{ $incidentLogs->count() }})
                </h5>
            </div>
            <div class="table-responsive">
                <table class="table table-custom table-sm align-middle mb-0">
                    <thead>
                        <tr>
                            <th>Website</th>
                            <th>Status</th>
                            <th>Error Details</th>
                            <th>Timestamp</th>
                            <th class="text-end">Evidence</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($incidentLogs as $iLog)
                            <tr>
                                <td class="fw-bold text-dark">{{ $iLog->website?->name }}</td>
                                <td>
                                    <span class="badge bg-danger badge-status">{{ strtoupper($iLog->status) }}</span>
                                </td>
                                <td class="small text-danger">{{ $iLog->error_message ?? 'Connection or assertion error' }}</td>
                                <td class="small text-muted">{{ $iLog->checked_at->format('d M Y, h:i:s A') }}</td>
                                <td class="text-end">
                                    <button class="btn btn-xs btn-outline-dark py-0 px-2" onclick="inspectLog({{ $iLog->id }})">
                                        <i class="bi bi-camera"></i> Inspect
                                    </button>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    @endif

@endsection
