<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;

class Report extends Model
{
    use HasFactory;

    protected $table = 'reports';

    protected $fillable = [
        'title',
        'period_from',
        'period_to',
        'total_checks',
        'successful_checks',
        'failed_checks',
        'uptime_percentage',
        'generated_by',
    ];

    protected $casts = [
        'period_from' => 'date',
        'period_to' => 'date',
        'total_checks' => 'integer',
        'successful_checks' => 'integer',
        'failed_checks' => 'integer',
        'uptime_percentage' => 'float',
        'generated_by' => 'integer',
    ];

    /**
     * Relationship: Has many ReportWebsites
     */
    public function reportWebsites(): HasMany
    {
        return $this->hasMany(ReportWebsite::class, 'report_id');
    }

    /**
     * Relationship: Generated by User
     */
    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class, 'generated_by');
    }
}
